# DB ?? ??
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##OHGIRAFFERS
    password: OHGIRAFFERS
# JPA ??
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        format_sql: true